version: '3'
services:

  angular-app:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: Front-end

  model-service:
    build:
      context: ./ModelService
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    container_name: Model-Service


  ingestion-service:
    build:
      context: ./IngestionService
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - USER_NAME=neo4j
      - PASSWORD=aziz1234
    depends_on:
      - neo-db
    container_name: Ingestion-Service


  retrieval-service:
    build:
      context: ./RetrievalService
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - USER_NAME=neo4j
      - PASSWORD=aziz1234
    depends_on:
      - neo-db
    container_name: Retrieval-Service
  

  generation-service:
    build:
      context: ./GenerationService
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    container_name: Generation-Service


  bff:
    build:
      context: ./BFF
      dockerfile: Dockerfile
    ports:
      - 8004:8004
    container_name: BFF
  

  neo-db:
    image: neo4j:5.20-community
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/aziz1234
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    container_name: neo4j-database


  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    restart: always
    container_name: ollama


volumes:
  neo4j_data:
  neo4j_plugins:
  ollama:
